version: '3.8'
services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  # api:
  #   build: ./server
  #   ports:
  #     - 5080:5080
